# Generated by Django 5.2.1 on 2025-05-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corriere',
            fields=[
                ('id_corriere', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('capacità_massima', models.IntegerField()),
                ('area_di_copertura_geografica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id_ordine', models.AutoField(primary_key=True, serialize=False)),
                ('data_e_ora_ordine', models.DateField()),
                ('indirizzo', models.CharField(max_length=100)),
                ('stato', models.CharField(choices=[('DA_ASSEGNARE', 'Da Assegnare'), ('ASSEGNATO', 'Assegnato'), ('TRANSITO', 'In Transito'), ('IN_CONSEGNA', 'In Consegna'), ('COMPLETATO', 'Completato')], default='DA_AS', max_length=20)),
                ('priorita', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BASSA', 'Bassa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id_veicolo', models.AutoField(primary_key=True, serialize=False)),
                ('Codice_Corriere', models.CharField(max_length=100)),
                ('capacità_massima', models.IntegerField()),
                ('Targa_mezzo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consegna',
            fields=[
                ('id_consegna', models.AutoField(primary_key=True, serialize=False)),
                ('id_corriere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corriere', to='corrieri.corriere')),
                ('id_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consegna', to='corrieri.ordine')),
                ('id_veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veicolo', to='corrieri.veicolo')),
            ],
        ),
    ]
