# Generated by Django 5.2.1 on 2025-06-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrieri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificaConsegna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine_id', models.IntegerField()),
                ('indirizzo', models.TextField()),
                ('data_consegna', models.DateTimeField()),
                ('corriere', models.CharField(max_length=100)),
                ('ricevuta_il', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ruolo', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='corriere',
            name='area_di_copertura_geografica',
        ),
        migrations.AddField(
            model_name='corriere',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corriere',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corriere',
            name='posizione_attuale',
            field=models.CharField(default='Non specificata', max_length=100),
        ),
        migrations.AddField(
            model_name='ordine',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordine',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='priorita',
            field=models.IntegerField(choices=[(10, 'Alta'), (5, 'Media'), (1, 'Bassa')]),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=models.CharField(choices=[('DA_ASSEGNARE', 'Da Assegnare'), ('ASSEGNATO', 'Assegnato'), ('TRANSITO', 'In Transito'), ('IN_CONSEGNA', 'In Consegna'), ('COMPLETATO', 'Completato')], default='DA_ASSEGNARE', max_length=20),
        ),
    ]
